require 'aquarium/aspects/advice'
require 'aquarium/aspects/aspect'
require 'aquarium/aspects/join_point'
require 'aquarium/aspects/pointcut'
require 'aquarium/aspects/pointcut_composition'
require 'aquarium/dsl'
