# Rakefile for the separate testing of JRuby support
# (Separate because we need to run JRuby, not MRI...)

require 'rubygems'
require 'rake'
require 'rake/clean'

# Use RSpec's files.
require 'spec/rake/spectask'
require 'spec/rake/verify_rcov'

task :default => [:jruby]

task :jruby => [:aquarium_spec, :jruby_spec] 

desc "Run all specs"
Spec::Rake::SpecTask.new do |t|
  t.spec_files = FileList['spec/**/*_spec.rb', 'examples/**/*_spec.rb']
end
task :spec => :verify_jruby

desc "Run all of aquarium's specs using JRuby"
task :aquarium_spec => :verify_jruby do
  output = nil
  Dir.chdir '..' do
    sh "rake spec_no_rcov"
  end
end

task :verify_jruby do
  unless self.class.const_defined? "JRUBY_VERSION"
    raise "ERROR: You must run these rake tasks with jruby."
  end
end

CLEAN.include('example.jar')
CLEAN.include('java/**/*.class')
SRC = FileList['java/**/*.java']
OBJ = SRC.ext('class')

rule '.class' => '.java' do |t|
  sh "javac -cp java #{t.source}"
end

file 'example.jar' => OBJ do
  sh 'jar -cf example.jar -C java .'
end

task :jruby_spec => ['example.jar', :spec]
